### ISSUE TITLE
pytz version comparison issues

### ISSUE THREAD

**Issue by teeberg** [dependencies-io/collector-python-pip#17]
pytz used to have a weird versioning scheme (it's much better now) that lead to this PR after I configured dependencies.io to pull in any versions (using `versions_regex: ".*"`). I "fixed" it for now using `versions: "Y.Y"`, but that seems to unnecessarily impose assumptions on their versioning scheme. I really just want to say "Pull in any update"

![image](https://user-images.githubusercontent.com/199071/37787464-372f8f18-2dbc-11e8-8035-baa10410e5b3.png)

**Comment by davegaeddert** [comment]
Thanks for the note on this. We're getting ready to release a whole bunch of new components for dependencies.io v2, so I'll probably copy this issue over to https://github.com/dependencies-io/python soon to make sure we don't lose sight of this.
